### ISSUE TITLE
visibility detection: false negatives

### ISSUE THREAD

**Issue by myrdd** [dascritch/anchors-reveal#10]
First of all, thank you for this add-on! I've found a bug, and I think it's quite easy to fix.

**Steps to reproduce:**

*  Install Anchors Reveal (AR) v0.4.1
* Go to https://www.debian.org/distrib/packages
* Press AR's button

**What happens:**

Mainly the form fields are marked by AR.

**What should happen:**

The headings should be marked as well.

---

Currently AR does these checks on each element having an ID:

```javascript
    function(el) {
      if (
          (el.id.indexOf(prefix)!==0) // not generated by the addon ?
          && ( valid_id.test(el.id) ) // not malicious ?
          && (!el.hidden) && (el.style.display !== 'none') // visible ?
          && ( (el.clientWidth != 0) && (el.clientHeight != 0 ) ) // really visible ?
        ) {
```

In this case all tests evaluate to `true`, but `clientWidth` and `clientHeight` are `false`.

I did some research and it looks like it's better to use `offsetWidth` and `offsetHeight`. JQuery additionally uses `getClientRects().length`, see [jquery's code](https://github.com/jquery/jquery/blob/c9cf250daafe806818da1dd207a88a8e94a4ad16/src/css/hiddenVisibleSelectors.js):

```javascript
jQuery.expr.filters.visible = function( elem ) {
	return !!( elem.offsetWidth || elem.offsetHeight || elem.getClientRects().length );
};
```

You might want to take that expression instead of the current ones. You could also remove usage of `el.hidden` and `el.style.display`.

MDN documentation: [`HTMLElement.offsetWidth`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth), [`HTMLElement.offsetHeight`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight), [`Element.getClientRects()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getClientRects).

**Comment by dascritch** [comment]
Oh !
Very good reporting ! 
Many thanks !

As I'm not actually really at home, due to very long and time-consuming projects , i'll really accept forks/patch/transmissions with this quality.

**Comment by myrdd** [comment]
Thanks for the quick reply. Sadly I can't create a pull request because the git repository only contains the XPI. Will you release a bugfix?

Btw, I see that [on AMO](https://addons.mozilla.org/en-US/firefox/addon/anchors-reveal/) there's still version 0.4, whereas there's also an unapproved [v0.5](https://addons.mozilla.org/en-US/firefox/addon/anchors-reveal/versions/0.5.1-signed). Do you need some help? I'm as well an extension developer.

**Comment by dascritch** [comment]
Didn't you saw the data/anchors-reveal.js ?

**Comment by myrdd** [comment]
You're right, I didn't look well enough. PR at #11.

Still, what about versions 0.5 and 0.6 on AMO?
