### ISSUE TITLE
Moving to WebExtension

### ISSUE THREAD

**Issue by dascritch** [dascritch/anchors-reveal#13]

**Comment by makyen** [comment]
I actually moved this to a WebExtension for my own use some time ago, with the intent of submitting a PR. I've been using it as a WebExtension for a few months. I'd intended to submit a pull request, but doing so slipped off my list of things to do. I'm happy to do so today/tomorrow. Do you want it, or have you already worked on making this transition?

If you do want the PR, how do you want the code organized? Do you want to completely abandon the Add-on SDK code (i.e. have it only available when looking at older revisions of the repository)? Do you want the WebExtensions code to live alongside the Add-on SDK code?

**Comment by dascritch** [comment]
Hi Makyen !

Very thanks for the help, this is the good side of open source ;)
In fact, I just opened this ticket because i'm still using my extension, but I also have Firefox Nightly. And  as the portage seems not so complicated, It was just a memo for me to tak action later.

But, please, you're welcome !

I think the old version must be discarded. Or perhaps, moved to a `legacy` branch ?

**Comment by dascritch** [comment]
Invalidates https://github.com/dascritch/anchors-reveal/issues/5

**Comment by dascritch** [comment]
Blog post to come ;)

**Comment by dascritch** [comment]
Blogged here (in french) https://dascritch.net/post/2017/09/04/Les-joies-de-la-communaut%C3%A9-open-source
So much thanks, Makyen !
