### ISSUE TITLE
Spelling oopses

### ISSUE THREAD

**Issue by mikini** [dascritch/anchors-reveal#23]
License name in README.md:
Purpose -> Public

In the [AMO](https://addons.mozilla.org/en-US/firefox/addon/anchors-reveal/) description:
clic -> click

Also the AMO description could be a little more elaborate, non-web developers might not know exactly what an anchor is.

**Comment by dascritch** [comment]
^^; as you guess, i have to practice a little more often my english. About the description of an anchor, yes, i have to explain a little better. Perhaps a link to MDN , or do an english translation of my original post <https://dascritch.net/post/2014/06/24/Sniffeur-d-ancre>

What do you seem the most legit ?

**Comment by mikini** [comment]
Well, I'm not at all French speaking but the Google Translation was quite understandable.

I think it'll be too many words for the AMO description, though. Just a short and precise description of what it does covering a couple of sentences, and then some references (I like spewing links too).
